{% set name = "thermo" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cc9993d2467ef3e31b9def6b8e20c9d257ba87051a86c43e8f61fba3f813896

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - fluids >=1.0.3
    - scipy
    - coolprop
    - pint
    - chemicals

test:
  requires:
    - sympy
    - matplotlib-base

  imports:
    - thermo
    - chemicals
    - fluids

about:
  home: https://github.com/CalebBell/thermo
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Chemical properties component of Chemical Engineering Design Library (ChEDL)
  description: |
    thermo is an open-source software for engineers, scientists, technicians and 
    anyone trying to understand the universe in more detail. It facilitates the 
    retrieval of constants of chemicals, the calculation of temperature and 
    pressure dependent chemical properties (both thermodynamic and transport), 
    the calculation of the same for chemical mixtures (including phase equilibria), 
    and assorted information of a regulatory or legal nature about chemicals.

    The thermo library depends on the SciPy library to provide numerical 
    constants, interpolation, integration, differentiation, and numerical 
    solving functionality. thermo all operating systems which support Python, is 
    quick to install, and is free of charge. thermo is designed to be easy 
    to use while still providing powerful functionality. If you need to know 
    something about a chemical, give thermo a try.
  doc_url: https://thermo.readthedocs.io/
  dev_url: https://github.com/CalebBell/thermo

extra:
  recipe-maintainers:
    - volpatto
    - CalebBell
